### ISSUE TITLE
Try different dictation methods

### ISSUE THREAD

**Issue by ulrichzglr** [WeibelLab-Teaching/CSE218_Fa19_ARengers#20]

**Comment by ruw001** [comment]
I tried different implementations for dictation recognition. But here's what I found on MRTK's doc:

> The dictation system uses Unity's DictationRecognizer which itself uses the underlying Windows speech APIs for handling dictation. Note that this implies that this feature is only present on Windows-based platforms.

which means the 2 methods are basicly identical... So we can choose either one. According to my experiments, the MRTK dictation recognizer has more functionalities. But it will automatically stop processing (not stop recording) after the recorded audio length reaches the limit. I'll try to fix that next week.

**Comment by RuWang15** [comment]
The recording time is the upper bound of the length of audio. There's a bug (according to Danilo) in MRTK's dictation system that prevent the dictation recognizer restarting once it completes processing.

Current work around is to use another thread to track the status of the current dictation system after it completes, and manually call `start()` when it's ready. It almost works. The only problem now is the little lag between the dictation system's stop and restart. Now I'm trying to solve the problem.

**Comment by ruw001** [comment]
Finally we switched to speech SDK in Azure cognitive service. It's faster and way more accurate.
